### ISSUE TITLE
Auto start node / iojs server after vagrant boot

### ISSUE THREAD

**Issue by sixlive** [renobit/vagrant-node-env#1]
Feature Request / Discussion

First, nice work on the box. I've built a bunch of handful for stock development and this is pretty solid (good chance I'll end up using this at some point).

For my node dev environments I typically have a boot script that starts up a forever instance of the node server. This could easily be added in the provisioner script. I would write the script to the ubuntu base box and then add the call to the rc.local init.

Just a thought, I could write something and issue a pull request.

Thanks for sharing your vagrant!

**Comment by davidmyersdev** [comment]
Thanks for the feedback! I was actually thinking about setting up a separate postinstall.sh script that ran under the vagrant user after provisioning. This could definitely be something to put in that script, but I'd like a little more information about it if you don't mind. 

Do you mean that a forever instance of `server.js` under the `/home/vagrant/www` directory should be started? If so, I had thought about doing this, but I actually planned for the environment to be able to house more than one project, in which case, you wouldn't want a single project instance to always run. I do plan on adding a variety of options to the postinstall script though.

I appreciate the ideas!

**Comment by sixlive** [comment]
I guess it really depends on your workflow. I typically setup one vagrant instance per project. Vagrant is great for just general local development (drop in replacement for WAMP, XAMPP, MAMP) however, I use it to mirror production so that my development environment matches, or is as close as possible to, production so nothing unexpected happens upon deploy.

You could setup a separate provision directive, possibly an environmental variable, to tell a start script inside the box the path to the node server/app file.

**Comment by davidmyersdev** [comment]
I also like to match it to my production server, but I was intending on this being a more general development environment for project bootstrapping and prototyping. I really appreciate the idea about adding a process manager though, and one is now included! 

As I stated earlier, I'm going to add the option to auto start the server in the `postinstall.sh` script though, so be sure to keep a look out for that! I'm going to close this, but if you have anything else to add, feel free to keep commenting. Thanks again!

**Comment by sixlive** [comment]
No worries, let me know if you need any help or have any questions I'm glad to lend a hand.
