### ISSUE TITLE
Isolated post install provisioning shell script

### ISSUE THREAD

**Issue by r4j4h** [renobit/vagrant-node-env#3]
The `npm install` phase of provisioning could be moved into a separate shell script so that newcomers have an easier time understanding what is going on and where things fit in the process. Helpful in learning and customization. Also could provide a first step towards supporting multiple different provisioning configurations with the same scaffolding.

**Comment by davidmyersdev** [comment]
Thanks for the idea! I was planning to simplify things a bit, so I'll go ahead and start working on this soon.

**Comment by davidmyersdev** [comment]
All right! This is now taken care of, and you can customize postinstall.sh to include whatever packages you need! Just keep in mind that postinstall.sh is run as the vagrant user and not as root.

**Comment by r4j4h** [comment]
Excellent work! :+1:

**Comment by davidmyersdev** [comment]
Thanks! I appreciate the feedback!
